DROP TABLE `Category`;
DROP TABLE `Contract`;
DROP TABLE `ContractEmployeeType`;
DROP TABLE `ContractService`;
DROP TABLE `ContractType`;
DROP TABLE `Employee`;
DROP TABLE `HoursMonths`;
DROP TABLE `SalaryType`;
DROP TABLE `Service`;